/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace FireInsurance {
  export type EventStruct = {
    timestamp: BigNumberish;
    deviceId: string;
    propertyId: string;
    temperature: BigNumberish;
    smokeLevel: BigNumberish;
    flameDetected: boolean;
    verified: boolean;
  };

  export type EventStructOutput = [
    timestamp: bigint,
    deviceId: string,
    propertyId: string,
    temperature: bigint,
    smokeLevel: bigint,
    flameDetected: boolean,
    verified: boolean
  ] & {
    timestamp: bigint;
    deviceId: string;
    propertyId: string;
    temperature: bigint;
    smokeLevel: bigint;
    flameDetected: boolean;
    verified: boolean;
  };
}

export interface FireInsuranceInterface extends Interface {
  getFunction(
    nameOrSignature: "events" | "getEvent" | "registerEvent"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EventRegistered"): EventFragment;

  encodeFunctionData(functionFragment: "events", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getEvent", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerEvent",
    values: [string, string, BigNumberish, BigNumberish, boolean, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "events", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerEvent",
    data: BytesLike
  ): Result;
}

export namespace EventRegisteredEvent {
  export type InputTuple = [eventId: BytesLike, approved: boolean];
  export type OutputTuple = [eventId: string, approved: boolean];
  export interface OutputObject {
    eventId: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FireInsurance extends BaseContract {
  connect(runner?: ContractRunner | null): FireInsurance;
  waitForDeployment(): Promise<this>;

  interface: FireInsuranceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  events: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, string, bigint, bigint, boolean, boolean] & {
        timestamp: bigint;
        deviceId: string;
        propertyId: string;
        temperature: bigint;
        smokeLevel: bigint;
        flameDetected: boolean;
        verified: boolean;
      }
    ],
    "view"
  >;

  getEvent: TypedContractMethod<
    [id: BytesLike],
    [FireInsurance.EventStructOutput],
    "view"
  >;

  registerEvent: TypedContractMethod<
    [
      deviceId: string,
      propertyId: string,
      temperature: BigNumberish,
      smokeLevel: BigNumberish,
      flameDetected: boolean,
      verified: boolean
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "events"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, string, bigint, bigint, boolean, boolean] & {
        timestamp: bigint;
        deviceId: string;
        propertyId: string;
        temperature: bigint;
        smokeLevel: bigint;
        flameDetected: boolean;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvent"
  ): TypedContractMethod<
    [id: BytesLike],
    [FireInsurance.EventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerEvent"
  ): TypedContractMethod<
    [
      deviceId: string,
      propertyId: string,
      temperature: BigNumberish,
      smokeLevel: BigNumberish,
      flameDetected: boolean,
      verified: boolean
    ],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "EventRegistered"
  ): TypedContractEvent<
    EventRegisteredEvent.InputTuple,
    EventRegisteredEvent.OutputTuple,
    EventRegisteredEvent.OutputObject
  >;

  filters: {
    "EventRegistered(bytes32,bool)": TypedContractEvent<
      EventRegisteredEvent.InputTuple,
      EventRegisteredEvent.OutputTuple,
      EventRegisteredEvent.OutputObject
    >;
    EventRegistered: TypedContractEvent<
      EventRegisteredEvent.InputTuple,
      EventRegisteredEvent.OutputTuple,
      EventRegisteredEvent.OutputObject
    >;
  };
}
