/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FireInsurance } from "./FireInsurance";
export * as factories from "./factories";
export { FireInsurance__factory } from "./factories/FireInsurance__factory";
